package bean;
// Generated 27/09/2023 15:19:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteMgoo generated by hbm2java
 */
@Entity
@Table(name="Cliente_mgoo"
    ,catalog="db_mireli_orlando"
)
public class ClienteMgoo  implements java.io.Serializable {


     private int idClienteMgoo;
     private String nomeMgoo;
     private String apelidoMgoo;
     private String cpfMgoo;
     private Date dataNascimentoMgoo;
     private String rgMgoo;
     private String emailMgoo;
     private int sexoMgoo;
     private String telefoneMgoo;
     private String celularMgoo;
     private String renavamMgoo;
     private int tipoPagamentoMgoo;
     private String cepMgoo;
     private String enderecoMgoo;
     private String complementoMgoo;
     

    public ClienteMgoo() {
    }

	
    public ClienteMgoo(int idClienteMgoo, String nomeMgoo, String apelidoMgoo, String cpfMgoo, Date dataNascimentoMgoo, String rgMgoo, String emailMgoo, int sexoMgoo, String telefoneMgoo, String celularMgoo, String renavamMgoo, int tipoPagamentoMgoo, String cepMgoo, String enderecoMgoo, String complementoMgoo) {
        this.idClienteMgoo = idClienteMgoo;
        this.nomeMgoo = nomeMgoo;
        this.apelidoMgoo = apelidoMgoo;
        this.cpfMgoo = cpfMgoo;
        this.dataNascimentoMgoo = dataNascimentoMgoo;
        this.rgMgoo = rgMgoo;
        this.emailMgoo = emailMgoo;
        this.sexoMgoo = sexoMgoo;
        this.telefoneMgoo = telefoneMgoo;
        this.celularMgoo = celularMgoo;
        this.renavamMgoo = renavamMgoo;
        this.tipoPagamentoMgoo = tipoPagamentoMgoo;
        this.cepMgoo = cepMgoo;
        this.enderecoMgoo = enderecoMgoo;
        this.complementoMgoo = complementoMgoo;
    }
    public ClienteMgoo(int idClienteMgoo, String nomeMgoo, String apelidoMgoo, String cpfMgoo, Date dataNascimentoMgoo, String rgMgoo, String emailMgoo, int sexoMgoo, String telefoneMgoo, String celularMgoo, String renavamMgoo, int tipoPagamentoMgoo, String cepMgoo, String enderecoMgoo, String complementoMgoo, Set vendaMgoos) {
       this.idClienteMgoo = idClienteMgoo;
       this.nomeMgoo = nomeMgoo;
       this.apelidoMgoo = apelidoMgoo;
       this.cpfMgoo = cpfMgoo;
       this.dataNascimentoMgoo = dataNascimentoMgoo;
       this.rgMgoo = rgMgoo;
       this.emailMgoo = emailMgoo;
       this.sexoMgoo = sexoMgoo;
       this.telefoneMgoo = telefoneMgoo;
       this.celularMgoo = celularMgoo;
       this.renavamMgoo = renavamMgoo;
       this.tipoPagamentoMgoo = tipoPagamentoMgoo;
       this.cepMgoo = cepMgoo;
       this.enderecoMgoo = enderecoMgoo;
       this.complementoMgoo = complementoMgoo;
      
    }
   
     @Id 

    
    @Column(name="idCliente_mgoo", unique=true, nullable=false)
    public int getIdClienteMgoo() {
        return this.idClienteMgoo;
    }
    
    public void setIdClienteMgoo(int idClienteMgoo) {
        this.idClienteMgoo = idClienteMgoo;
    }

    
    @Column(name="nome_mgoo", nullable=false, length=100)
    public String getNomeMgoo() {
        return this.nomeMgoo;
    }
    
    public void setNomeMgoo(String nomeMgoo) {
        this.nomeMgoo = nomeMgoo;
    }

    
    @Column(name="apelido_mgoo", nullable=false, length=45)
    public String getApelidoMgoo() {
        return this.apelidoMgoo;
    }
    
    public void setApelidoMgoo(String apelidoMgoo) {
        this.apelidoMgoo = apelidoMgoo;
    }

    
    @Column(name="cpf_mgoo", nullable=false, length=45)
    public String getCpfMgoo() {
        return this.cpfMgoo;
    }
    
    public void setCpfMgoo(String cpfMgoo) {
        this.cpfMgoo = cpfMgoo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_mgoo", nullable=false, length=10)
    public Date getDataNascimentoMgoo() {
        return this.dataNascimentoMgoo;
    }
    
    public void setDataNascimentoMgoo(Date dataNascimentoMgoo) {
        this.dataNascimentoMgoo = dataNascimentoMgoo;
    }

    
    @Column(name="rg_mgoo", nullable=false, length=45)
    public String getRgMgoo() {
        return this.rgMgoo;
    }
    
    public void setRgMgoo(String rgMgoo) {
        this.rgMgoo = rgMgoo;
    }

    
    @Column(name="email_mgoo", nullable=false, length=100)
    public String getEmailMgoo() {
        return this.emailMgoo;
    }
    
    public void setEmailMgoo(String emailMgoo) {
        this.emailMgoo = emailMgoo;
    }

    
    @Column(name="sexo_mgoo", nullable=false)
    public int getSexoMgoo() {
        return this.sexoMgoo;
    }
    
    public void setSexoMgoo(int sexoMgoo) {
        this.sexoMgoo = sexoMgoo;
    }

    
    @Column(name="telefone_mgoo", nullable=false, length=45)
    public String getTelefoneMgoo() {
        return this.telefoneMgoo;
    }
    
    public void setTelefoneMgoo(String telefoneMgoo) {
        this.telefoneMgoo = telefoneMgoo;
    }

    
    @Column(name="celular_mgoo", nullable=false, length=45)
    public String getCelularMgoo() {
        return this.celularMgoo;
    }
    
    public void setCelularMgoo(String celularMgoo) {
        this.celularMgoo = celularMgoo;
    }

    
    @Column(name="renavam_mgoo", nullable=false, length=45)
    public String getRenavamMgoo() {
        return this.renavamMgoo;
    }
    
    public void setRenavamMgoo(String renavamMgoo) {
        this.renavamMgoo = renavamMgoo;
    }

    
    @Column(name="tipoPagamento_mgoo", nullable=false)
    public int getTipoPagamentoMgoo() {
        return this.tipoPagamentoMgoo;
    }
    
    public void setTipoPagamentoMgoo(int tipoPagamentoMgoo) {
        this.tipoPagamentoMgoo = tipoPagamentoMgoo;
    }

    
    @Column(name="cep_mgoo", nullable=false, length=45)
    public String getCepMgoo() {
        return this.cepMgoo;
    }
    
    public void setCepMgoo(String cepMgoo) {
        this.cepMgoo = cepMgoo;
    }

    
    @Column(name="endereco_mgoo", nullable=false, length=100)
    public String getEnderecoMgoo() {
        return this.enderecoMgoo;
    }
    
    public void setEnderecoMgoo(String enderecoMgoo) {
        this.enderecoMgoo = enderecoMgoo;
    }

    
    @Column(name="complemento_mgoo", nullable=false, length=150)
    public String getComplementoMgoo() {
        return this.complementoMgoo;
    }
    
    public void setComplementoMgoo(String complementoMgoo) {
        this.complementoMgoo = complementoMgoo;
    }






}


