package bean;
// Generated 27/09/2023 15:19:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProdutoMgoo generated by hbm2java
 */
@Entity
@Table(name="Produto_mgoo"
    ,catalog="db_mireli_orlando"
)
public class ProdutoMgoo  implements java.io.Serializable {


     private int idProdutoMgoo;
     private String marcaMgoo;
     private String modeloMgoo;
     private Date anoFabricacaoMgoo;
     private String corMgoo;
     private int portasMgoo;
     private String combustivelMgoo;
     private String motorMgoo;
     private double valorMgoo;
    

    public ProdutoMgoo() {
    }

	
    public ProdutoMgoo(int idProdutoMgoo, String marcaMgoo, String modeloMgoo, Date anoFabricacaoMgoo, String corMgoo, int portasMgoo, String combustivelMgoo, String motorMgoo, double valorMgoo) {
        this.idProdutoMgoo = idProdutoMgoo;
        this.marcaMgoo = marcaMgoo;
        this.modeloMgoo = modeloMgoo;
        this.anoFabricacaoMgoo = anoFabricacaoMgoo;
        this.corMgoo = corMgoo;
        this.portasMgoo = portasMgoo;
        this.combustivelMgoo = combustivelMgoo;
        this.motorMgoo = motorMgoo;
        this.valorMgoo = valorMgoo;
    }
    public ProdutoMgoo(int idProdutoMgoo, String marcaMgoo, String modeloMgoo, Date anoFabricacaoMgoo, String corMgoo, int portasMgoo, String combustivelMgoo, String motorMgoo, double valorMgoo, Set vendasProdutoMgoos) {
       this.idProdutoMgoo = idProdutoMgoo;
       this.marcaMgoo = marcaMgoo;
       this.modeloMgoo = modeloMgoo;
       this.anoFabricacaoMgoo = anoFabricacaoMgoo;
       this.corMgoo = corMgoo;
       this.portasMgoo = portasMgoo;
       this.combustivelMgoo = combustivelMgoo;
       this.motorMgoo = motorMgoo;
       this.valorMgoo = valorMgoo;
     
    }
   
     @Id 

    
    @Column(name="idProduto_mgoo", unique=true, nullable=false)
    public int getIdProdutoMgoo() {
        return this.idProdutoMgoo;
    }
    
    public void setIdProdutoMgoo(int idProdutoMgoo) {
        this.idProdutoMgoo = idProdutoMgoo;
    }

    
    @Column(name="marca_mgoo", nullable=false, length=150)
    public String getMarcaMgoo() {
        return this.marcaMgoo;
    }
    
    public void setMarcaMgoo(String marcaMgoo) {
        this.marcaMgoo = marcaMgoo;
    }

    
    @Column(name="modelo_mgoo", nullable=false, length=150)
    public String getModeloMgoo() {
        return this.modeloMgoo;
    }
    
    public void setModeloMgoo(String modeloMgoo) {
        this.modeloMgoo = modeloMgoo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="anoFabricacao_mgoo", nullable=false, length=10)
    public Date getAnoFabricacaoMgoo() {
        return this.anoFabricacaoMgoo;
    }
    
    public void setAnoFabricacaoMgoo(Date anoFabricacaoMgoo) {
        this.anoFabricacaoMgoo = anoFabricacaoMgoo;
    }

    
    @Column(name="cor_mgoo", nullable=false, length=45)
    public String getCorMgoo() {
        return this.corMgoo;
    }
    
    public void setCorMgoo(String corMgoo) {
        this.corMgoo = corMgoo;
    }

    
    @Column(name="portas_mgoo", nullable=false)
    public int getPortasMgoo() {
        return this.portasMgoo;
    }
    
    public void setPortasMgoo(int portasMgoo) {
        this.portasMgoo = portasMgoo;
    }

    
    @Column(name="combustivel_mgoo", nullable=false, length=45)
    public String getCombustivelMgoo() {
        return this.combustivelMgoo;
    }
    
    public void setCombustivelMgoo(String combustivelMgoo) {
        this.combustivelMgoo = combustivelMgoo;
    }

    
    @Column(name="motor_mgoo", nullable=false, length=45)
    public String getMotorMgoo() {
        return this.motorMgoo;
    }
    
    public void setMotorMgoo(String motorMgoo) {
        this.motorMgoo = motorMgoo;
    }

    
    @Column(name="valor_mgoo", nullable=false, precision=22, scale=0)
    public double getValorMgoo() {
        return this.valorMgoo;
    }
    
    public void setValorMgoo(double valorMgoo) {
        this.valorMgoo = valorMgoo;
    }






}


