package bean;
// Generated 27/09/2023 15:19:29 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosMgoo generated by hbm2java
 */
@Entity
@Table(name="Usuarios_mgoo"
    ,catalog="db_mireli_orlando"
)
public class UsuariosMgoo  implements java.io.Serializable {


     private int idUsuariosMgoo;
     private String nomeMgoo;
     private String apelidoMgoo;
     private String cpfMgoo;
     private Date dataNascimentoMgoo;
     private String senhaMgoo;
     private int nivelMgoo;
     private String ativoMgoo;

    public UsuariosMgoo() {
    }

    public UsuariosMgoo(int idUsuariosMgoo, String nomeMgoo, String apelidoMgoo, String cpfMgoo, Date dataNascimentoMgoo, String senhaMgoo, int nivelMgoo, String ativoMgoo) {
       this.idUsuariosMgoo = idUsuariosMgoo;
       this.nomeMgoo = nomeMgoo;
       this.apelidoMgoo = apelidoMgoo;
       this.cpfMgoo = cpfMgoo;
       this.dataNascimentoMgoo = dataNascimentoMgoo;
       this.senhaMgoo = senhaMgoo;
       this.nivelMgoo = nivelMgoo;
       this.ativoMgoo = ativoMgoo;
    }
   
     @Id 

    
    @Column(name="idUsuarios_mgoo", unique=true, nullable=false)
    public int getIdUsuariosMgoo() {
        return this.idUsuariosMgoo;
    }
    
    public void setIdUsuariosMgoo(int idUsuariosMgoo) {
        this.idUsuariosMgoo = idUsuariosMgoo;
    }

    
    @Column(name="nome_mgoo", nullable=false, length=100)
    public String getNomeMgoo() {
        return this.nomeMgoo;
    }
    
    public void setNomeMgoo(String nomeMgoo) {
        this.nomeMgoo = nomeMgoo;
    }

    
    @Column(name="apelido_mgoo", nullable=false, length=45)
    public String getApelidoMgoo() {
        return this.apelidoMgoo;
    }
    
    public void setApelidoMgoo(String apelidoMgoo) {
        this.apelidoMgoo = apelidoMgoo;
    }

    
    @Column(name="cpf_mgoo", nullable=false, length=45)
    public String getCpfMgoo() {
        return this.cpfMgoo;
    }
    
    public void setCpfMgoo(String cpfMgoo) {
        this.cpfMgoo = cpfMgoo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_mgoo", nullable=false, length=10)
    public Date getDataNascimentoMgoo() {
        return this.dataNascimentoMgoo;
    }
    
    public void setDataNascimentoMgoo(Date dataNascimentoMgoo) {
        this.dataNascimentoMgoo = dataNascimentoMgoo;
    }

    
    @Column(name="senha_mgoo", nullable=false, length=100)
    public String getSenhaMgoo() {
        return this.senhaMgoo;
    }
    
    public void setSenhaMgoo(String senhaMgoo) {
        this.senhaMgoo = senhaMgoo;
    }

    
    @Column(name="nivel_mgoo", nullable=false)
    public int getNivelMgoo() {
        return this.nivelMgoo;
    }
    
    public void setNivelMgoo(int nivelMgoo) {
        this.nivelMgoo = nivelMgoo;
    }

    
    @Column(name="ativo_mgoo", nullable=false, length=45)
    public String getAtivoMgoo() {
        return this.ativoMgoo;
    }
    
    public void setAtivoMgoo(String ativoMgoo) {
        this.ativoMgoo = ativoMgoo;
    }




}


