package bean;
// Generated 27/09/2023 15:19:29 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasProdutoMgoo generated by hbm2java
 */
@Entity
@Table(name="Vendas_produto_mgoo"
    ,catalog="db_mireli_orlando"
)
public class VendasProdutoMgoo  implements java.io.Serializable {


     private int idVendasProdutoMgoo;
     private ProdutoMgoo produtoMgoo;
     private VendaMgoo vendaMgoo;
     private Date dataVendaMgoo;
     private int quantidadeMgoo;
     private double valorUnitarioMgoo;

    public VendasProdutoMgoo() {
    }

    public VendasProdutoMgoo(int idVendasProdutoMgoo, ProdutoMgoo produtoMgoo, VendaMgoo vendaMgoo, Date dataVendaMgoo, int quantidadeMgoo, double valorUnitarioMgoo) {
       this.idVendasProdutoMgoo = idVendasProdutoMgoo;
       this.produtoMgoo = produtoMgoo;
       this.vendaMgoo = vendaMgoo;
       this.dataVendaMgoo = dataVendaMgoo;
       this.quantidadeMgoo = quantidadeMgoo;
       this.valorUnitarioMgoo = valorUnitarioMgoo;
    }
   
     @Id 

    
    @Column(name="idVendas_produto_mgoo", unique=true, nullable=false)
    public int getIdVendasProdutoMgoo() {
        return this.idVendasProdutoMgoo;
    }
    
    public void setIdVendasProdutoMgoo(int idVendasProdutoMgoo) {
        this.idVendasProdutoMgoo = idVendasProdutoMgoo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_mgoo", nullable=false)
    public ProdutoMgoo getProdutoMgoo() {
        return this.produtoMgoo;
    }
    
    public void setProdutoMgoo(ProdutoMgoo produtoMgoo) {
        this.produtoMgoo = produtoMgoo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="venda_mgoo", nullable=false)
    public VendaMgoo getVendaMgoo() {
        return this.vendaMgoo;
    }
    
    public void setVendaMgoo(VendaMgoo vendaMgoo) {
        this.vendaMgoo = vendaMgoo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVenda_mgoo", nullable=false, length=10)
    public Date getDataVendaMgoo() {
        return this.dataVendaMgoo;
    }
    
    public void setDataVendaMgoo(Date dataVendaMgoo) {
        this.dataVendaMgoo = dataVendaMgoo;
    }

    
    @Column(name="quantidade_mgoo", nullable=false)
    public int getQuantidadeMgoo() {
        return this.quantidadeMgoo;
    }
    
    public void setQuantidadeMgoo(int quantidadeMgoo) {
        this.quantidadeMgoo = quantidadeMgoo;
    }

    
    @Column(name="valorUnitario_mgoo", nullable=false, precision=22, scale=0)
    public double getValorUnitarioMgoo() {
        return this.valorUnitarioMgoo;
    }
    
    public void setValorUnitarioMgoo(double valorUnitarioMgoo) {
        this.valorUnitarioMgoo = valorUnitarioMgoo;
    }




}


