package bean;
// Generated 27/09/2023 15:19:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendaMgoo generated by hbm2java
 */
@Entity
@Table(name="Venda_mgoo"
    ,catalog="db_mireli_orlando"
)
public class VendaMgoo  implements java.io.Serializable {


     private int idVendaMgoo;
     private ClienteMgoo clienteMgoo;
     private VendedorMgoo vendedorMgoo;
     private Date dataMgoo;
     private double valorTotalMgoo;
    

    public VendaMgoo() {
    }

	
    public VendaMgoo(int idVendaMgoo, ClienteMgoo clienteMgoo, VendedorMgoo vendedorMgoo, Date dataMgoo, double valorTotalMgoo) {
        this.idVendaMgoo = idVendaMgoo;
        this.clienteMgoo = clienteMgoo;
        this.vendedorMgoo = vendedorMgoo;
        this.dataMgoo = dataMgoo;
        this.valorTotalMgoo = valorTotalMgoo;
    }
    public VendaMgoo(int idVendaMgoo, ClienteMgoo clienteMgoo, VendedorMgoo vendedorMgoo, Date dataMgoo, double valorTotalMgoo, Set vendasProdutoMgoos) {
       this.idVendaMgoo = idVendaMgoo;
       this.clienteMgoo = clienteMgoo;
       this.vendedorMgoo = vendedorMgoo;
       this.dataMgoo = dataMgoo;
       this.valorTotalMgoo = valorTotalMgoo;
    }
   
     @Id 

    
    @Column(name="idVenda_mgoo", unique=true, nullable=false)
    public int getIdVendaMgoo() {
        return this.idVendaMgoo;
    }
    
    public void setIdVendaMgoo(int idVendaMgoo) {
        this.idVendaMgoo = idVendaMgoo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_mgoo", nullable=false)
    public ClienteMgoo getClienteMgoo() {
        return this.clienteMgoo;
    }
    
    public void setClienteMgoo(ClienteMgoo clienteMgoo) {
        this.clienteMgoo = clienteMgoo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor_mgoo", nullable=false)
    public VendedorMgoo getVendedorMgoo() {
        return this.vendedorMgoo;
    }
    
    public void setVendedorMgoo(VendedorMgoo vendedorMgoo) {
        this.vendedorMgoo = vendedorMgoo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_mgoo", nullable=false, length=10)
    public Date getDataMgoo() {
        return this.dataMgoo;
    }
    
    public void setDataMgoo(Date dataMgoo) {
        this.dataMgoo = dataMgoo;
    }

    
    @Column(name="valorTotal_mgoo", nullable=false, precision=22, scale=0)
    public double getValorTotalMgoo() {
        return this.valorTotalMgoo;
    }
    
    public void setValorTotalMgoo(double valorTotalMgoo) {
        this.valorTotalMgoo = valorTotalMgoo;
    }






}


