package bean;
// Generated 27/09/2023 15:19:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendedorMgoo generated by hbm2java
 */
@Entity
@Table(name="Vendedor_mgoo"
    ,catalog="db_mireli_orlando"
)
public class VendedorMgoo  implements java.io.Serializable {


     private int idVendedorMgoo;
     private String nomeMgoo;
     private String apelidoMgoo;
     private String cpfMgoo;
     private String rgMgoo;
     private Date dataNascimentoMgoo;
     private String telefoneMgoo;
     private String celularMgoo;
    

    public VendedorMgoo() {
    }

	
    public VendedorMgoo(int idVendedorMgoo, String nomeMgoo, String apelidoMgoo, String cpfMgoo, String rgMgoo, Date dataNascimentoMgoo, String telefoneMgoo, String celularMgoo) {
        this.idVendedorMgoo = idVendedorMgoo;
        this.nomeMgoo = nomeMgoo;
        this.apelidoMgoo = apelidoMgoo;
        this.cpfMgoo = cpfMgoo;
        this.rgMgoo = rgMgoo;
        this.dataNascimentoMgoo = dataNascimentoMgoo;
        this.telefoneMgoo = telefoneMgoo;
        this.celularMgoo = celularMgoo;
    }
    public VendedorMgoo(int idVendedorMgoo, String nomeMgoo, String apelidoMgoo, String cpfMgoo, String rgMgoo, Date dataNascimentoMgoo, String telefoneMgoo, String celularMgoo, Set vendaMgoos) {
       this.idVendedorMgoo = idVendedorMgoo;
       this.nomeMgoo = nomeMgoo;
       this.apelidoMgoo = apelidoMgoo;
       this.cpfMgoo = cpfMgoo;
       this.rgMgoo = rgMgoo;
       this.dataNascimentoMgoo = dataNascimentoMgoo;
       this.telefoneMgoo = telefoneMgoo;
       this.celularMgoo = celularMgoo;
      
    }
   
     @Id 

    
    @Column(name="idVendedor_mgoo", unique=true, nullable=false)
    public int getIdVendedorMgoo() {
        return this.idVendedorMgoo;
    }
    
    public void setIdVendedorMgoo(int idVendedorMgoo) {
        this.idVendedorMgoo = idVendedorMgoo;
    }

    
    @Column(name="nome_mgoo", nullable=false, length=100)
    public String getNomeMgoo() {
        return this.nomeMgoo;
    }
    
    public void setNomeMgoo(String nomeMgoo) {
        this.nomeMgoo = nomeMgoo;
    }

    
    @Column(name="apelido_mgoo", nullable=false, length=45)
    public String getApelidoMgoo() {
        return this.apelidoMgoo;
    }
    
    public void setApelidoMgoo(String apelidoMgoo) {
        this.apelidoMgoo = apelidoMgoo;
    }

    
    @Column(name="cpf_mgoo", nullable=false, length=45)
    public String getCpfMgoo() {
        return this.cpfMgoo;
    }
    
    public void setCpfMgoo(String cpfMgoo) {
        this.cpfMgoo = cpfMgoo;
    }

    
    @Column(name="rg_mgoo", nullable=false, length=45)
    public String getRgMgoo() {
        return this.rgMgoo;
    }
    
    public void setRgMgoo(String rgMgoo) {
        this.rgMgoo = rgMgoo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_mgoo", nullable=false, length=10)
    public Date getDataNascimentoMgoo() {
        return this.dataNascimentoMgoo;
    }
    
    public void setDataNascimentoMgoo(Date dataNascimentoMgoo) {
        this.dataNascimentoMgoo = dataNascimentoMgoo;
    }

    
    @Column(name="telefone_mgoo", nullable=false, length=45)
    public String getTelefoneMgoo() {
        return this.telefoneMgoo;
    }
    
    public void setTelefoneMgoo(String telefoneMgoo) {
        this.telefoneMgoo = telefoneMgoo;
    }

    
    @Column(name="celular_mgoo", nullable=false, length=45)
    public String getCelularMgoo() {
        return this.celularMgoo;
    }
    
    public void setCelularMgoo(String celularMgoo) {
        this.celularMgoo = celularMgoo;
    }


}


